spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST}/ohsul
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      show-sql: true
