spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST}/ohsul
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    aws:
      s3:
        bucket: ohsul
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false
      credentials:
        accessKey: ${ACCESSKEY}
        secretKey: ${SECRETKEY}
server:
  ssl:

    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: {PKCSPW}
    keyAlias: ohsulbecert
  port: 8443